# Generated by Django 6.0.4 on 2026-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_candidate_jobdescription_matchscore_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_filename', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('ml_score', models.FloatField(help_text='ML match score (0-100)')),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('verdict', models.CharField(max_length=50)),
                ('method', models.CharField(default='tfidf_cosine', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ML Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
