# Generated by Django 5.2.4 on 2026-04-18 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_mlanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
