# Generated by Django 5.2.4 on 2026-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_candidate_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='default', max_length=255),
        ),
    ]
